n=(input('digite algo: '))
print('oq vc digitou e da clase:',type(n))
print(n.isidentifier())
print(n.isnumeric())
print(n.isspace())
print(n.isalnum())
print(n.isalpha())
print(n.isdecimal())
print(n.isupper())
print(n.isprintable())